name: copilot-run-integration-tests

on:
  workflow_dispatch:
    inputs:
      BACKEND_HOST:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string
  workflow_call:
    inputs:
      BACKEND_HOST:
        required: true
        type: string
      ENVIRONMENT:
        required: true
        type: string

permissions:
  contents: read

jobs:
  tests:
    environment: ${{inputs.ENVIRONMENT}}
    name: Integration Testing
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure test environment
        working-directory: integration-tests
        env:
          TestUsername: ${{secrets.COPILOT_CHAT_TEST_USER_ACCOUNT1}}
          TestPassword: ${{secrets.COPILOT_CHAT_TEST_USER_PASSWORD1}}
        run: |
          dotnet user-secrets set "BaseServerUrl" "https://${{inputs.BACKEND_HOST}}.azurewebsites.net/"
          dotnet user-secrets set "Authority" "https://login.microsoftonline.com/${{vars.APPLICATION_TENANT_ID}}"
          dotnet user-secrets set "ClientID" ${{vars.APPLICATION_CLIENT_ID}}
          dotnet user-secrets set "Scopes" "openid, offline_access, profile, api://${{vars.BACKEND_CLIENT_ID}}/access_as_user"
          # dotnet user-secrets set "TestUsername" "$env:TestUsername"
          # dotnet user-secrets set "TestPassword" "$env:TestPassword"

      - name: Run integration tests
        run: dotnet test --logger trx
